/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/bryant/wpi_sample_return_robot_challenge/beaglebone_node/src/rosserial/rosserial_msgs/srv/RequestMessageInfo.srv
 *
 */


#ifndef ROSSERIAL_MSGS_MESSAGE_REQUESTMESSAGEINFO_H
#define ROSSERIAL_MSGS_MESSAGE_REQUESTMESSAGEINFO_H

#include <ros/service_traits.h>


#include <rosserial_msgs/RequestMessageInfoRequest.h>
#include <rosserial_msgs/RequestMessageInfoResponse.h>


namespace rosserial_msgs
{

struct RequestMessageInfo
{

typedef RequestMessageInfoRequest Request;
typedef RequestMessageInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RequestMessageInfo
} // namespace rosserial_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosserial_msgs::RequestMessageInfo > {
  static const char* value()
  {
    return "6416d80296dfbbdd5f7b2cee839f9316";
  }

  static const char* value(const ::rosserial_msgs::RequestMessageInfo&) { return value(); }
};

template<>
struct DataType< ::rosserial_msgs::RequestMessageInfo > {
  static const char* value()
  {
    return "rosserial_msgs/RequestMessageInfo";
  }

  static const char* value(const ::rosserial_msgs::RequestMessageInfo&) { return value(); }
};


// service_traits::MD5Sum< ::rosserial_msgs::RequestMessageInfoRequest> should match 
// service_traits::MD5Sum< ::rosserial_msgs::RequestMessageInfo > 
template<>
struct MD5Sum< ::rosserial_msgs::RequestMessageInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosserial_msgs::RequestMessageInfo >::value();
  }
  static const char* value(const ::rosserial_msgs::RequestMessageInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosserial_msgs::RequestMessageInfoRequest> should match 
// service_traits::DataType< ::rosserial_msgs::RequestMessageInfo > 
template<>
struct DataType< ::rosserial_msgs::RequestMessageInfoRequest>
{
  static const char* value()
  {
    return DataType< ::rosserial_msgs::RequestMessageInfo >::value();
  }
  static const char* value(const ::rosserial_msgs::RequestMessageInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosserial_msgs::RequestMessageInfoResponse> should match 
// service_traits::MD5Sum< ::rosserial_msgs::RequestMessageInfo > 
template<>
struct MD5Sum< ::rosserial_msgs::RequestMessageInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosserial_msgs::RequestMessageInfo >::value();
  }
  static const char* value(const ::rosserial_msgs::RequestMessageInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosserial_msgs::RequestMessageInfoResponse> should match 
// service_traits::DataType< ::rosserial_msgs::RequestMessageInfo > 
template<>
struct DataType< ::rosserial_msgs::RequestMessageInfoResponse>
{
  static const char* value()
  {
    return DataType< ::rosserial_msgs::RequestMessageInfo >::value();
  }
  static const char* value(const ::rosserial_msgs::RequestMessageInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSSERIAL_MSGS_MESSAGE_REQUESTMESSAGEINFO_H
