(cl:defpackage rgbdslam-srv
  (:use )
  (:export
   "RGBDSLAM_ROS_UI"
   "<RGBDSLAM_ROS_UI-REQUEST>"
   "RGBDSLAM_ROS_UI-REQUEST"
   "<RGBDSLAM_ROS_UI-RESPONSE>"
   "RGBDSLAM_ROS_UI-RESPONSE"
   "RGBDSLAM_ROS_UI_B"
   "<RGBDSLAM_ROS_UI_B-REQUEST>"
   "RGBDSLAM_ROS_UI_B-REQUEST"
   "<RGBDSLAM_ROS_UI_B-RESPONSE>"
   "RGBDSLAM_ROS_UI_B-RESPONSE"
   "RGBDSLAM_ROS_UI_F"
   "<RGBDSLAM_ROS_UI_F-REQUEST>"
   "RGBDSLAM_ROS_UI_F-REQUEST"
   "<RGBDSLAM_ROS_UI_F-RESPONSE>"
   "RGBDSLAM_ROS_UI_F-RESPONSE"
   "RGBDSLAM_ROS_UI_S"
   "<RGBDSLAM_ROS_UI_S-REQUEST>"
   "RGBDSLAM_ROS_UI_S-REQUEST"
   "<RGBDSLAM_ROS_UI_S-RESPONSE>"
   "RGBDSLAM_ROS_UI_S-RESPONSE"
  ))

