/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/bryant/wpi_sample_return_robot_challenge/beaglebone_node/src/rosserial/rosserial_arduino/srv/Test.srv
 *
 */


#ifndef ROSSERIAL_ARDUINO_MESSAGE_TEST_H
#define ROSSERIAL_ARDUINO_MESSAGE_TEST_H

#include <ros/service_traits.h>


#include <rosserial_arduino/TestRequest.h>
#include <rosserial_arduino/TestResponse.h>


namespace rosserial_arduino
{

struct Test
{

typedef TestRequest Request;
typedef TestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Test
} // namespace rosserial_arduino


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosserial_arduino::Test > {
  static const char* value()
  {
    return "c63e85f503b805d84df783e71c6bb0d2";
  }

  static const char* value(const ::rosserial_arduino::Test&) { return value(); }
};

template<>
struct DataType< ::rosserial_arduino::Test > {
  static const char* value()
  {
    return "rosserial_arduino/Test";
  }

  static const char* value(const ::rosserial_arduino::Test&) { return value(); }
};


// service_traits::MD5Sum< ::rosserial_arduino::TestRequest> should match 
// service_traits::MD5Sum< ::rosserial_arduino::Test > 
template<>
struct MD5Sum< ::rosserial_arduino::TestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosserial_arduino::Test >::value();
  }
  static const char* value(const ::rosserial_arduino::TestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosserial_arduino::TestRequest> should match 
// service_traits::DataType< ::rosserial_arduino::Test > 
template<>
struct DataType< ::rosserial_arduino::TestRequest>
{
  static const char* value()
  {
    return DataType< ::rosserial_arduino::Test >::value();
  }
  static const char* value(const ::rosserial_arduino::TestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosserial_arduino::TestResponse> should match 
// service_traits::MD5Sum< ::rosserial_arduino::Test > 
template<>
struct MD5Sum< ::rosserial_arduino::TestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosserial_arduino::Test >::value();
  }
  static const char* value(const ::rosserial_arduino::TestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosserial_arduino::TestResponse> should match 
// service_traits::DataType< ::rosserial_arduino::Test > 
template<>
struct DataType< ::rosserial_arduino::TestResponse>
{
  static const char* value()
  {
    return DataType< ::rosserial_arduino::Test >::value();
  }
  static const char* value(const ::rosserial_arduino::TestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSSERIAL_ARDUINO_MESSAGE_TEST_H
