#!/bin/bash

#
INCLUDEDIRS="-I/usr/include/opencv -I/usr/include"
LIBDIRS="-L/opt/ros/hydro/lib -L/usr/local/lib"
LIBS="-lopencv_calib3d -lopencv_contrib -lopencv_core -lopencv_features2d -lopencv_flann -lopencv_gpu -lopencv_highgui -lopencv_imgproc -lopencv_legacy -lopencv_ml -lopencv_nonfree -lopencv_objdetect -lopencv_photo -lopencv_stitching -lopencv_ts -lopencv_video -lopencv_videostab"

# compile
if [ $# -lt 2 ]; then
    g++ -ggdb $INCLUDEDIRS $1 $LIBDIRS $LIBS
else
    g++ -ggdb $INCLUDEDIRS $1 -o $2 $LIBDIRS $LIBS
fi





