/* Auto-generated by genmsg_cpp for file /home/will/Code/wpi-sample-return-robot-challenge/rockie_code/src/rgbdslam-hydro-master/rgbdslam/srv/rgbdslam_ros_ui_f.srv */
#ifndef RGBDSLAM_SERVICE_RGBDSLAM_ROS_UI_F_H
#define RGBDSLAM_SERVICE_RGBDSLAM_ROS_UI_F_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace rgbdslam
{
template <class ContainerAllocator>
struct rgbdslam_ros_ui_fRequest_ {
  typedef rgbdslam_ros_ui_fRequest_<ContainerAllocator> Type;

  rgbdslam_ros_ui_fRequest_()
  : command()
  , value(0.0)
  {
  }

  rgbdslam_ros_ui_fRequest_(const ContainerAllocator& _alloc)
  : command(_alloc)
  , value(0.0)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _command_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  command;

  typedef float _value_type;
  float value;


  typedef boost::shared_ptr< ::rgbdslam::rgbdslam_ros_ui_fRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rgbdslam::rgbdslam_ros_ui_fRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct rgbdslam_ros_ui_fRequest
typedef  ::rgbdslam::rgbdslam_ros_ui_fRequest_<std::allocator<void> > rgbdslam_ros_ui_fRequest;

typedef boost::shared_ptr< ::rgbdslam::rgbdslam_ros_ui_fRequest> rgbdslam_ros_ui_fRequestPtr;
typedef boost::shared_ptr< ::rgbdslam::rgbdslam_ros_ui_fRequest const> rgbdslam_ros_ui_fRequestConstPtr;



template <class ContainerAllocator>
struct rgbdslam_ros_ui_fResponse_ {
  typedef rgbdslam_ros_ui_fResponse_<ContainerAllocator> Type;

  rgbdslam_ros_ui_fResponse_()
  {
  }

  rgbdslam_ros_ui_fResponse_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::rgbdslam::rgbdslam_ros_ui_fResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rgbdslam::rgbdslam_ros_ui_fResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct rgbdslam_ros_ui_fResponse
typedef  ::rgbdslam::rgbdslam_ros_ui_fResponse_<std::allocator<void> > rgbdslam_ros_ui_fResponse;

typedef boost::shared_ptr< ::rgbdslam::rgbdslam_ros_ui_fResponse> rgbdslam_ros_ui_fResponsePtr;
typedef boost::shared_ptr< ::rgbdslam::rgbdslam_ros_ui_fResponse const> rgbdslam_ros_ui_fResponseConstPtr;


struct rgbdslam_ros_ui_f
{

typedef rgbdslam_ros_ui_fRequest Request;
typedef rgbdslam_ros_ui_fResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct rgbdslam_ros_ui_f
} // namespace rgbdslam

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::rgbdslam::rgbdslam_ros_ui_fRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::rgbdslam::rgbdslam_ros_ui_fRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::rgbdslam::rgbdslam_ros_ui_fRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d8f674e014809463d0a122a49c328a89";
  }

  static const char* value(const  ::rgbdslam::rgbdslam_ros_ui_fRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd8f674e014809463ULL;
  static const uint64_t static_value2 = 0xd0a122a49c328a89ULL;
};

template<class ContainerAllocator>
struct DataType< ::rgbdslam::rgbdslam_ros_ui_fRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rgbdslam/rgbdslam_ros_ui_fRequest";
  }

  static const char* value(const  ::rgbdslam::rgbdslam_ros_ui_fRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::rgbdslam::rgbdslam_ros_ui_fRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string command\n\
float32 value\n\
\n\
";
  }

  static const char* value(const  ::rgbdslam::rgbdslam_ros_ui_fRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::rgbdslam::rgbdslam_ros_ui_fResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::rgbdslam::rgbdslam_ros_ui_fResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::rgbdslam::rgbdslam_ros_ui_fResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::rgbdslam::rgbdslam_ros_ui_fResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::rgbdslam::rgbdslam_ros_ui_fResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rgbdslam/rgbdslam_ros_ui_fResponse";
  }

  static const char* value(const  ::rgbdslam::rgbdslam_ros_ui_fResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::rgbdslam::rgbdslam_ros_ui_fResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::rgbdslam::rgbdslam_ros_ui_fResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::rgbdslam::rgbdslam_ros_ui_fResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::rgbdslam::rgbdslam_ros_ui_fRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.command);
    stream.next(m.value);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct rgbdslam_ros_ui_fRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::rgbdslam::rgbdslam_ros_ui_fResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct rgbdslam_ros_ui_fResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<rgbdslam::rgbdslam_ros_ui_f> {
  static const char* value() 
  {
    return "d8f674e014809463d0a122a49c328a89";
  }

  static const char* value(const rgbdslam::rgbdslam_ros_ui_f&) { return value(); } 
};

template<>
struct DataType<rgbdslam::rgbdslam_ros_ui_f> {
  static const char* value() 
  {
    return "rgbdslam/rgbdslam_ros_ui_f";
  }

  static const char* value(const rgbdslam::rgbdslam_ros_ui_f&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<rgbdslam::rgbdslam_ros_ui_fRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d8f674e014809463d0a122a49c328a89";
  }

  static const char* value(const rgbdslam::rgbdslam_ros_ui_fRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<rgbdslam::rgbdslam_ros_ui_fRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rgbdslam/rgbdslam_ros_ui_f";
  }

  static const char* value(const rgbdslam::rgbdslam_ros_ui_fRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<rgbdslam::rgbdslam_ros_ui_fResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d8f674e014809463d0a122a49c328a89";
  }

  static const char* value(const rgbdslam::rgbdslam_ros_ui_fResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<rgbdslam::rgbdslam_ros_ui_fResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rgbdslam/rgbdslam_ros_ui_f";
  }

  static const char* value(const rgbdslam::rgbdslam_ros_ui_fResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // RGBDSLAM_SERVICE_RGBDSLAM_ROS_UI_F_H

